### ISSUE TITLE
Instructions unclear: Click on " view panorama"

### ISSUE THREAD

**Issue by XekriRedmane** [SiliconAnalysis/xystitch#36]
There is no such button. Here's what I get when I start hugin via `xy-hugin out.pto`:
<img width="1401" alt="hugin" src="https://user-images.githubusercontent.com/1783950/141697692-39435321-dc7a-4b12-8bef-cfa035536d82.PNG">

**Comment by XekriRedmane** [comment]
It seems that this allows me to make progress:

* Hit "2. Align..."
* Hit "3. Create panorama...", hit OK. 
  * Hugin displays another dialog saying it will need to save the project. Hit OK.
  * Hugin opens a file browser. Just hit Save.
  * Hugin does more processing. It brings up a "Batch Processor" window. Wait until the status bar at the bottom of that window says "Batch successfully completed."
  * Close the Batch Processor window.
* I don't know when you're supposed to use the Crop tab. Before or after hitting "Create panorama"?

**Comment by JohnDMcMaster** [comment]
I've added more detailed instructions to cover Basic vs Expert GUI mode. Please take a look at latest README and let me know if that helps

**Comment by JohnDMcMaster** [comment]
Sounds like this is resolved, but please let me know if otherwise.
